config/routes.rb
Examplea::Application.routes.draw do

  devise_for :admins, :path => "admin", :skip => [:registrations], :controllers => { :sessions => "admins/sessions" }
    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      get 'admin', :to => 'admin#index', :as => :admin_root
    end
  apipie
  namespace :api do
    namespace :v1 do
      
        resources :examaobjectmodels
      
    end # v1

namespace :v2 do
      
        resources :examaobjectmodels
      
    end # v2

    namespace :v3 do
      
        resources :examaobjectmodels
      
    end # v3

    # Mount rails engine gems.
    
  end

  namespace :admin do
    
      resources :examaobjectmodels
    
  end

  get '/admin/extensions' => 'admin/extensions#index'

  get '/admin' => 'admin#index'

  root :to => 'admin#index'

  # Catch all for unmatched API routes.
  match '/api/*unmatched_route', to: 'api/api#raise_not_found!'
end

app/views/admin/_admin_sidebar.html.haml
.list-group
  
  
  
  = link_to 'Examaobjectmodels', admin_examaobjectmodels_path, class: "list-group-item #{'active' if active == 'Examaobjectmodels'}"
  
  

app/views/admin/index.html.haml
.page-header
  %h1 Welcome
= row do
  = col_md 7 do
    %p.lead
      Welcome to the admin console.  From here you can manage admin users,
      application data, extensions, and view API documentation.
  = col_md 5 do
    = panel heading: 'Base API' do
      %code https://obscure-harbor-6682.herokuapp.com/api/v3


= row do
  = col_md 7 do
    = table do
      %thead
        %tr
          %th Object
          %th.text-right Count
      %tbody
        
        %tr
          
          %td= link_to 'Examaobjectmodels', admin_examaobjectmodels_path
          
          %td.text-right
            
            .text-muted= V3::Examaobjectmodel.count
            
        