config/routes.rb
Examplea::Application.routes.draw do

  devise_for :admins, :path => "admin", :skip => [:registrations], :controllers => { :sessions => "admins/sessions" }
    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      get 'admin', :to => 'admin#index', :as => :admin_root
    end
  apipie
  namespace :api do
    namespace :v1 do
      
        resources :examaobjectmodels
      
    end # v1

namespace :v2 do
      
        resources :examaobjectmodels
      
    end # v2

    namespace :v3 do
      
        resources :examaobjectmodels
      
    end # v3

    # Mount rails engine gems.
    
  end

  namespace :admin do
    
      resources :examaobjectmodels
    
  end

  get '/admin/extensions' => 'admin/extensions#index'

  get '/admin' => 'admin#index'

  root :to => 'admin#index'

  # Catch all for unmatched API routes.
  match '/api/*unmatched_route', to: 'api/api#raise_not_found!'
end

app/controllers/admin/extensions_controller.rb
class Admin::ExtensionsController < ApplicationController
  before_filter :authenticate_admin!
  layout 'admin'

end

app/views/admin/extensions/index.html.haml
%ul.breadcrumb
  %li
    = link_to 'Home', admin_root_path
    
  %li.active Extensions

.page-header
  %h1 Extensions

%p
  Extensions add additional functionality to your app.  Manage your extensions
  here.

.alert
  %i.fa.fa-info
  %strong No extensions installed.