config/routes.rb
Examplea::Application.routes.draw do

  devise_for :admins, :path => "admin", :skip => [:registrations], :controllers => { :sessions => "admins/sessions" }
    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      get 'admin', :to => 'admin#index', :as => :admin_root
    end
  apipie
  namespace :api do
    namespace :v1 do
      
        resources :examaobjectmodels
      
    end # v1

namespace :v2 do
      
        resources :examaobjectmodels
      
    end # v2

    namespace :v3 do
      
        resources :examaobjectmodels
      
    end # v3

    # Mount rails engine gems.
    
  end

  namespace :admin do
    
      resources :examaobjectmodels
    
  end

  get '/admin/extensions' => 'admin/extensions#index'

  get '/admin' => 'admin#index'

  root :to => 'admin#index'

  # Catch all for unmatched API routes.
  match '/api/*unmatched_route', to: 'api/api#raise_not_found!'
end

app/views/layouts/admin.html.haml
!!!
%html{lang: 'en', 'xml:lang' => 'en', xmlns: 'http://www.w3.org/1999/xhtml'}
  %head
    %title Examplea
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  %body
    .header
      - if current_admin
        .navbar.navbar-inverse
          .navbar-header
            %button.navbar-toggle{data: {toggle: 'collapse', target: '.navbar-ex1-collapse'}}
              %span.sr-only Toggle navigation
              %span.fa.fa-bars
            .navbar-brand
              API v3
          .collapse.navbar-collapse.navbar-ex1-collapse
            %ul.nav.navbar-nav
              %li= link_to 'Home', main_app.admin_root_path
              %li= link_to 'Documentation', main_app.apipie_path
              %li= link_to 'Extensions', main_app.admin_extensions_path
            %ul.nav.navbar-nav.pull-right
              %li= link_to current_admin.email, main_app.edit_admin_registration_path
              %li= link_to "Sign out", main_app.destroy_admin_session_path, :method => :delete
    
    .container
      = yield

app/views/layouts/application.html.haml
!!!
%html{lang: 'en', 'xml:lang' => 'en', xmlns: 'http://www.w3.org/1999/xhtml'}
  %head
    %title Examplea
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = content_tag :script, '', type: 'text/javascript', src: (request.ssl? ? 'https' : 'http') + '://maps.google.com/maps/api/js?sensor=true'
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = javascript_tag "if (window.Ext) {Ext.Ajax.extraParams = { authenticity_token: '#{form_authenticity_token}' };}"
  %body
    .container
      = yield

app/views/layouts/devise.haml
!!!
%html{lang: :en, 'xml:lang' => 'en', xmlns: 'http://www.w3.org/1999/xhtml'}
  %head
    %title Examplea
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
    %meta{content: 'width=device-width, initial-scale=1', name: 'viewport'}
  %body
    .header
      - if current_admin
        .navbar.navbar-inverse
          .navbar-header
            %button.navbar-toggle{data: {toggle: 'collapse', target: '.navbar-ex1-collapse'}}
              %span.sr-only Toggle navigation
              %span.fa.fa-bars
            .navbar-brand API
          .collapse.navbar-collapse.navbar-ex1-collapse
            %ul.nav.navbar-nav
              %li= link_to 'Home', main_app.admin_root_path
              %li= link_to 'Documentation', main_app.apipie_path
              %li= link_to 'Extensions', main_app.admin_extensions_path
            %ul.nav.navbar-nav.pull-right
              %li= link_to current_admin.email, main_app.edit_admin_registration_path
              %li= link_to "Sign out", main_app.destroy_admin_session_path, :method => :delete

    .container
      - if current_admin
        = yield
      - else
        %br
        = row do
          = col_md 6, {offset: 3} do
            = yield

app/views/layouts/documentation.html.haml
!!!
%html{lang: 'en', 'xml:lang' => 'en', xmlns: 'http://www.w3.org/1999/xhtml'}
  %head
    %title Examplea
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
  %body
    .header
      - if current_admin
        .navbar.navbar-inverse
          .navbar-header
            %button.navbar-toggle{data: {toggle: 'collapse', target: '.navbar-ex1-collapse'}}
              %span.sr-only Toggle navigation
              %span.fa.fa-bars
            .navbar-brand
              API v3
          .collapse.navbar-collapse.navbar-ex1-collapse
            %ul.nav.navbar-nav
              %li= link_to 'Home', main_app.admin_root_path
              %li= link_to 'Documentation', main_app.apipie_path
              %li= link_to 'Extensions', main_app.admin_extensions_path
            %ul.nav.navbar-nav.pull-right
              %li= link_to current_admin.email, main_app.edit_admin_registration_path
              %li= link_to "Sign out", main_app.destroy_admin_session_path, :method => :delete
    
    .container
      = yield
    
    .container
      %footer
        = yield :apipie_footer